CREATE ROLE AppAdmin;
GRANT CONTROL ON DATABASE::DatanautDB TO AppAdmin;

CREATE ROLE AppProjectManager;
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON Project TO AppProjectManager;
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON TimeLogs TO AppProjectManager;
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON ProjectResource TO AppProjectManager;
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON Equipment TO AppProjectManager;
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON Software TO AppProjectManager;
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON License TO AppProjectManager;
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON ProjectTeam TO AppProjectManager;

CREATE ROLE AppEmployer;
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON TimeLogs TO AppEmployer;